version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: graphql-api
    ports:
      - "4000:4000"
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
    env_file:
      - .env
    depends_on:
      - messaging
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  messaging:
    build: ./messaging-service
    container_name: messaging-service
    env_file:
      - ./messaging-service/.env
    depends_on:
      - redis
    restart: always
    volumes:
      - ./messaging-service/prisma/logs.db:/app/prisma/logs.db
    healthcheck:
      test: ["CMD-SHELL", "node -e 'require(\"./src/worker\")' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5
