# --------------------- Types --------------------#

enum Score {
  Bad
  Okay
  Good
  Excellent
}

type Rating {
  id: ID!
  score: Score
  comment: String
  createdAt: String!
  userId: ID!
}

# --------------------- Inputs --------------------#

input CreateRatingInput {
  userId: String!
  orderId: String!
  score: Score!
  comment: String
}

# --------------------- Responses --------------------#

type CreateRatingResponse {
  status: ResponseStatus
  data: Rating
}

# --------------------- Queries --------------------#

type Query {
  getRatingsByUser(userId: ID!): [Rating!]!
  getRatingById(id: ID!): Rating
}

# --------------------- Mutations --------------------#

type Mutation {
  createRating(input: CreateRatingInput!): Rating!
}
