# --------------------- Types --------------------#

type Rating {
  id: ID!
  comment: String
  createdAt: String!
  service: Int
  quality: Int
  overall: Int
  userId: ID!
}

# --------------------- Inputs --------------------#

input CreateRatingInput {
  userId: String!
  orderId: String!
  service: Int!
  quality: Int!
  comment: String
}

# --------------------- Responses --------------------#

type CreateRatingResponse {
  status: ResponseStatus
  data: Rating
}

# --------------------- Queries --------------------#

type Query {
  getRatingsByUser(userId: ID!): [Rating!]!
  getRatingById(id: ID!): Rating
}

# --------------------- Mutations --------------------#

type Mutation {
  createRating(input: CreateRatingInput!): Rating!
}
