# --------------------- Types --------------------#

type User {
  id: ID!
  teamId: String
  name: String!
  email: String
  contactNumber: Int
}

# --------------------- Inputs --------------------#

input CreateUserInput {
  name: String!
  teamId: String
  email: String
  contactNumber: Int
}

input UpdateUserInput {
  id: ID!
  teamId: String
  name: String
  email: String
  contactNumber: Int
}

# --------------------- Responses --------------------#

type CreateUserResponse {
  status: ResponseStatus
  data: [User]
}

type UpdateUserResponse {
  status: ResponseStatus
  data: User
}


# --------------------- Queries --------------------#

type Query {
  get(userId: ID): User
  getAllUsers: [User]
}

# --------------------- Mutations --------------------#

type Mutation {
  createUser(input: CreateUserInput): User
  updateUser(input: UpdateUserInput): User
}
