# --------------------- Types --------------------- #

type Team {
  id: ID!
  name: String!
  members: [User]
}

# --------------------- Inputs --------------------- #

input CreateTeamInput {
  name: String!
  user: [CreateUserInput]
}

# --------------------- Queries --------------------- #

type Query {
  getAllTeamss: [Team]
}

# --------------------- Mutations --------------------- #

type Mutation {
  createTeam(input: CreateTeamInput!): Team!
}
