# --------------------- Types --------------------- #

type Team {
  id: ID!
  name: String!
  members: [User]
}

# --------------------- Inputs --------------------- #

input CreateTeamInput {
  name: String!
  members: [CreateUserInput]
}

type CreateTeamResponse {
  status: ResponseStatus
  data: Team
}

# --------------------- Queries --------------------- #

type Query {
  getAllTeams: [Team]
}

# --------------------- Mutations --------------------- #

type Mutation {
  createTeam(input: CreateTeamInput!): CreateTeamResponse
}
